[toolchain]
channel = "1.69.0"
components = [
  "cargo",
  "clippy",
  "rust-analyzer",
  "rust-src",
  "rust-std",
  "rustc-dev",
  "rustc",
  "rustfmt",
]
profile = "minimal"
targets = ["wasm32-unknown-unknown"]
